# Standalone build for the published repo. Generated by
# platform/tangled/publish/gen-standalone.nu; edit that template, not this file.
#
# Deliberately not the monorepo's default.nix. That one is a flakelight module
# too, but the root flake imports it and it reaches for ../../../platform/nix/lib, so it
# means nothing in a clone. This is the same shape, standing on its own.
{
  description = "Rust CLI for Tangled, a decentralized git collaboration platform built on the AT Protocol";

  inputs = {
    # Pinned to the same revision the monorepo resolves, so every published
    # repo builds against identical nixpkgs and they cannot drift apart.
    # Change it by re-running the generator, never here.
    nixpkgs.url = "github:NixOS/nixpkgs/fcb8fcd6bf2d0adecae5bd491afaaaf8311b758d";

    # The monorepo is a flakelight tree, so its published pieces are too.
    flakelight = {
      url = "github:accelbread/flakelight";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    git-hooks = {
      url = "github:cachix/git-hooks.nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = inputs: let
    # Read the crate's own manifest rather than restating it here. A workspace
    # root has no [package], and baseNameOf ./. would give the store path, so
    # the repo name is baked in as the fallback.
    cargoToml = builtins.fromTOML (builtins.readFile ./Cargo.toml);
    cargoPackage = cargoToml.package or {};
    name = cargoPackage.name or "tangled-cli";

    # The same gates in every published repo, so a contributor who has only
    # this one is held to what the monorepo holds it to. Generated from a
    # shared template rather than pulled from a common repo of ours: an input
    # would make entering this shell depend on a second repo of ours, and the
    # point is that this one stands alone. Entering the shell installs them.
    hooksFor = pkgs:
      inputs.git-hooks.lib.${pkgs.stdenv.hostPlatform.system}.run {
        src = ./.;
        package = pkgs.prek;
        hooks = {
          rustfmt.enable = true;
          clippy.enable = true;
          typos.enable = true;
          ripsecrets.enable = true;
          alejandra.enable = true;
          deadnix.enable = true;
          statix.enable = true;
        };
      };
  in
    inputs.flakelight ./. {
      inherit inputs;
      systems = ["x86_64-linux" "aarch64-linux" "aarch64-darwin"];
      pname = name;

      # flakelight turns this into packages.default, a check, and an overlay,
      # so `nix flake check` builds it and the CI workflow needs nothing else.
      package = {
        rustPlatform,
        pkg-config,
        openssl,
        dbus,
      }:
        rustPlatform.buildRustPackage {
          pname = name;
          version = cargoPackage.version or "0.1.0";
          src = ./.;
          cargoLock = {
            lockFile = ./Cargo.lock;
            allowBuiltinFetchGit = true;
          };
          nativeBuildInputs = [pkg-config];
          buildInputs = [openssl dbus];
          # Tests need network access or a running server.
          doCheck = false;

          meta = {
            description = "Rust CLI for Tangled, a decentralized git collaboration platform built on the AT Protocol";
            mainProgram = name;
          };
        };

      devShell = {
        packages = pkgs:
          (with pkgs; [cargo rustc rust-analyzer clippy rustfmt])
          ++ (with pkgs; [pkg-config openssl dbus])
          ++ (hooksFor pkgs).enabledPackages;
        shellHook = pkgs: (hooksFor pkgs).shellHook;
      };

      formatter = pkgs: pkgs.alejandra;
    };
}
